Fix parsing of first title entry
f888ebf caused first title entry from KEYDB.cfg to be ignored as it is
trying to add entries to uninitialized list, and just prints following
warning:
Error: No title list passed as parameter.
Fix it by moving initialization to proper place.